// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7gV2UPK_1tW0crIj1Y5GBzEUQyII0qlg',
    appId: '1:607995566384:web:c718ebbb0306b9ac0850f5',
    messagingSenderId: '607995566384',
    projectId: 'jnvst-74bb1',
    authDomain: 'jnvst-74bb1.firebaseapp.com',
    storageBucket: 'jnvst-74bb1.appspot.com',
    measurementId: 'G-84G8663JEN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8qbnc9LN4grHu-9ESgAlvOzW_5KmXljY',
    appId: '1:607995566384:android:61a217640316b7dd0850f5',
    messagingSenderId: '607995566384',
    projectId: 'jnvst-74bb1',
    storageBucket: 'jnvst-74bb1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxu0w_YBS1rKs99HYXO8hBoPkLrty1dS0',
    appId: '1:607995566384:ios:53e5f433cd4ee3570850f5',
    messagingSenderId: '607995566384',
    projectId: 'jnvst-74bb1',
    storageBucket: 'jnvst-74bb1.appspot.com',
    iosBundleId: 'com.uht.jnvst.jnvstPrep',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxu0w_YBS1rKs99HYXO8hBoPkLrty1dS0',
    appId: '1:607995566384:ios:53e5f433cd4ee3570850f5',
    messagingSenderId: '607995566384',
    projectId: 'jnvst-74bb1',
    storageBucket: 'jnvst-74bb1.appspot.com',
    iosBundleId: 'com.uht.jnvst.jnvstPrep',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7gV2UPK_1tW0crIj1Y5GBzEUQyII0qlg',
    appId: '1:607995566384:web:30e036413f51731d0850f5',
    messagingSenderId: '607995566384',
    projectId: 'jnvst-74bb1',
    authDomain: 'jnvst-74bb1.firebaseapp.com',
    storageBucket: 'jnvst-74bb1.appspot.com',
    measurementId: 'G-YHGFGYW442',
  );
}
